/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WohnungsbauRouteImport } from './routes/wohnungsbau'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RenovierungRouteImport } from './routes/renovierung'
import { Route as NeugestaltungRouteImport } from './routes/neugestaltung'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const WohnungsbauRoute = WohnungsbauRouteImport.update({
  id: '/wohnungsbau',
  path: '/wohnungsbau',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovierungRoute = RenovierungRouteImport.update({
  id: '/renovierung',
  path: '/renovierung',
  getParentRoute: () => rootRouteImport,
} as any)
const NeugestaltungRoute = NeugestaltungRouteImport.update({
  id: '/neugestaltung',
  path: '/neugestaltung',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/neugestaltung': typeof NeugestaltungRoute
  '/renovierung': typeof RenovierungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wohnungsbau': typeof WohnungsbauRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/neugestaltung': typeof NeugestaltungRoute
  '/renovierung': typeof RenovierungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wohnungsbau': typeof WohnungsbauRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/neugestaltung': typeof NeugestaltungRoute
  '/renovierung': typeof RenovierungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wohnungsbau': typeof WohnungsbauRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/neugestaltung'
    | '/renovierung'
    | '/sitemap.xml'
    | '/wohnungsbau'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/neugestaltung'
    | '/renovierung'
    | '/sitemap.xml'
    | '/wohnungsbau'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/neugestaltung'
    | '/renovierung'
    | '/sitemap.xml'
    | '/wohnungsbau'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  NeugestaltungRoute: typeof NeugestaltungRoute
  RenovierungRoute: typeof RenovierungRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WohnungsbauRoute: typeof WohnungsbauRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wohnungsbau': {
      id: '/wohnungsbau'
      path: '/wohnungsbau'
      fullPath: '/wohnungsbau'
      preLoaderRoute: typeof WohnungsbauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovierung': {
      id: '/renovierung'
      path: '/renovierung'
      fullPath: '/renovierung'
      preLoaderRoute: typeof RenovierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neugestaltung': {
      id: '/neugestaltung'
      path: '/neugestaltung'
      fullPath: '/neugestaltung'
      preLoaderRoute: typeof NeugestaltungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  NeugestaltungRoute: NeugestaltungRoute,
  RenovierungRoute: RenovierungRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WohnungsbauRoute: WohnungsbauRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
